# Optional: GitHub sponsors
# github: [username]

# Optional: Other platforms
# patreon: username
# open_collective: projectname
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# custom: ['https://example.com', 'https://example2.com']
