// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: pkg/plugin/plugin.proto

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DSPlugin_GetManifest_FullMethodName    = "/plugin.DSPlugin/GetManifest"
	DSPlugin_Execute_FullMethodName        = "/plugin.DSPlugin/Execute"
	DSPlugin_ValidateConfig_FullMethodName = "/plugin.DSPlugin/ValidateConfig"
	DSPlugin_GetSchema_FullMethodName      = "/plugin.DSPlugin/GetSchema"
)

// DSPluginClient is the client API for DSPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DSPlugin service definition
type DSPluginClient interface {
	GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*GetManifestResponse, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
}

type dSPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewDSPluginClient(cc grpc.ClientConnInterface) DSPluginClient {
	return &dSPluginClient{cc}
}

func (c *dSPluginClient) GetManifest(ctx context.Context, in *GetManifestRequest, opts ...grpc.CallOption) (*GetManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetManifestResponse)
	err := c.cc.Invoke(ctx, DSPlugin_GetManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSPluginClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, DSPlugin_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSPluginClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, DSPlugin_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dSPluginClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, DSPlugin_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DSPluginServer is the server API for DSPlugin service.
// All implementations must embed UnimplementedDSPluginServer
// for forward compatibility.
//
// DSPlugin service definition
type DSPluginServer interface {
	GetManifest(context.Context, *GetManifestRequest) (*GetManifestResponse, error)
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	mustEmbedUnimplementedDSPluginServer()
}

// UnimplementedDSPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDSPluginServer struct{}

func (UnimplementedDSPluginServer) GetManifest(context.Context, *GetManifestRequest) (*GetManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedDSPluginServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedDSPluginServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedDSPluginServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedDSPluginServer) mustEmbedUnimplementedDSPluginServer() {}
func (UnimplementedDSPluginServer) testEmbeddedByValue()                  {}

// UnsafeDSPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DSPluginServer will
// result in compilation errors.
type UnsafeDSPluginServer interface {
	mustEmbedUnimplementedDSPluginServer()
}

func RegisterDSPluginServer(s grpc.ServiceRegistrar, srv DSPluginServer) {
	// If the following call pancis, it indicates UnimplementedDSPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DSPlugin_ServiceDesc, srv)
}

func _DSPlugin_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSPluginServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DSPlugin_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSPluginServer).GetManifest(ctx, req.(*GetManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSPlugin_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSPluginServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DSPlugin_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSPluginServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSPlugin_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSPluginServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DSPlugin_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSPluginServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DSPlugin_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DSPluginServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DSPlugin_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DSPluginServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DSPlugin_ServiceDesc is the grpc.ServiceDesc for DSPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DSPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.DSPlugin",
	HandlerType: (*DSPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManifest",
			Handler:    _DSPlugin_GetManifest_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _DSPlugin_Execute_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _DSPlugin_ValidateConfig_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _DSPlugin_GetSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/plugin.proto",
}

const (
	HostConfig_GetEffectiveConfig_FullMethodName = "/plugin.HostConfig/GetEffectiveConfig"
)

// HostConfigClient is the client API for HostConfig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostConfig exposes host-provided configuration to plugins over the gRPC broker
type HostConfigClient interface {
	GetEffectiveConfig(ctx context.Context, in *GetEffectiveConfigRequest, opts ...grpc.CallOption) (*GetEffectiveConfigResponse, error)
}

type hostConfigClient struct {
	cc grpc.ClientConnInterface
}

func NewHostConfigClient(cc grpc.ClientConnInterface) HostConfigClient {
	return &hostConfigClient{cc}
}

func (c *hostConfigClient) GetEffectiveConfig(ctx context.Context, in *GetEffectiveConfigRequest, opts ...grpc.CallOption) (*GetEffectiveConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEffectiveConfigResponse)
	err := c.cc.Invoke(ctx, HostConfig_GetEffectiveConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostConfigServer is the server API for HostConfig service.
// All implementations must embed UnimplementedHostConfigServer
// for forward compatibility.
//
// HostConfig exposes host-provided configuration to plugins over the gRPC broker
type HostConfigServer interface {
	GetEffectiveConfig(context.Context, *GetEffectiveConfigRequest) (*GetEffectiveConfigResponse, error)
	mustEmbedUnimplementedHostConfigServer()
}

// UnimplementedHostConfigServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostConfigServer struct{}

func (UnimplementedHostConfigServer) GetEffectiveConfig(context.Context, *GetEffectiveConfigRequest) (*GetEffectiveConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEffectiveConfig not implemented")
}
func (UnimplementedHostConfigServer) mustEmbedUnimplementedHostConfigServer() {}
func (UnimplementedHostConfigServer) testEmbeddedByValue()                    {}

// UnsafeHostConfigServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostConfigServer will
// result in compilation errors.
type UnsafeHostConfigServer interface {
	mustEmbedUnimplementedHostConfigServer()
}

func RegisterHostConfigServer(s grpc.ServiceRegistrar, srv HostConfigServer) {
	// If the following call pancis, it indicates UnimplementedHostConfigServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostConfig_ServiceDesc, srv)
}

func _HostConfig_GetEffectiveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEffectiveConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostConfigServer).GetEffectiveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostConfig_GetEffectiveConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostConfigServer).GetEffectiveConfig(ctx, req.(*GetEffectiveConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostConfig_ServiceDesc is the grpc.ServiceDesc for HostConfig service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostConfig_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.HostConfig",
	HandlerType: (*HostConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEffectiveConfig",
			Handler:    _HostConfig_GetEffectiveConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugin/plugin.proto",
}
