// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/plugin/plugin.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataRequest) Reset() {
	*x = GetMetadataRequest{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataRequest) ProtoMessage() {}

func (x *GetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{0}
}

type GetMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Operations    []string               `protobuf:"bytes,4,rep,name=operations,proto3" json:"operations,omitempty"`
	Platform      *Platform              `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Config        map[string]string      `protobuf:"bytes,6,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResponse) Reset() {
	*x = GetMetadataResponse{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResponse) ProtoMessage() {}

func (x *GetMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetMetadataResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetMetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetMetadataResponse) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *GetMetadataResponse) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *GetMetadataResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type Platform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            []string               `protobuf:"bytes,1,rep,name=os,proto3" json:"os,omitempty"`
	Arch          []string               `protobuf:"bytes,2,rep,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Platform) Reset() {
	*x = Platform{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Platform) GetOs() []string {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *Platform) GetArch() []string {
	if x != nil {
		return x.Arch
	}
	return nil
}

type ExecuteRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Operation          string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Args               []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Env                map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HostConfigBrokerId uint32                 `protobuf:"varint,4,opt,name=host_config_broker_id,json=hostConfigBrokerId,proto3" json:"host_config_broker_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ExecuteRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecuteRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecuteRequest) GetHostConfigBrokerId() uint32 {
	if x != nil {
		return x.HostConfigBrokerId
	}
	return 0
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdout        string                 `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Finalizers    []*FinalizerRequest    `protobuf:"bytes,5,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetFinalizers() []*FinalizerRequest {
	if x != nil {
		return x.Finalizers
	}
	return nil
}

type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateConfigRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{7}
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Version       string                     `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Properties    map[string]*SchemaProperty `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *GetSchemaResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetSchemaResponse) GetProperties() map[string]*SchemaProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

type SchemaProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	Default       string                 `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaProperty) Reset() {
	*x = SchemaProperty{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaProperty) ProtoMessage() {}

func (x *SchemaProperty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaProperty.ProtoReflect.Descriptor instead.
func (*SchemaProperty) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *SchemaProperty) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SchemaProperty) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SchemaProperty) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *SchemaProperty) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

type GetEffectiveConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEffectiveConfigRequest) Reset() {
	*x = GetEffectiveConfigRequest{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEffectiveConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEffectiveConfigRequest) ProtoMessage() {}

func (x *GetEffectiveConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEffectiveConfigRequest.ProtoReflect.Descriptor instead.
func (*GetEffectiveConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{10}
}

type GetEffectiveConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    []byte                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEffectiveConfigResponse) Reset() {
	*x = GetEffectiveConfigResponse{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEffectiveConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEffectiveConfigResponse) ProtoMessage() {}

func (x *GetEffectiveConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEffectiveConfigResponse.ProtoReflect.Descriptor instead.
func (*GetEffectiveConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *GetEffectiveConfigResponse) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type FinalizerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizerRequest) Reset() {
	*x = FinalizerRequest{}
	mi := &file_pkg_plugin_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizerRequest) ProtoMessage() {}

func (x *FinalizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugin_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizerRequest.ProtoReflect.Descriptor instead.
func (*FinalizerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugin_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *FinalizerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FinalizerRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *FinalizerRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_pkg_plugin_plugin_proto protoreflect.FileDescriptor

const file_pkg_plugin_plugin_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/plugin/plugin.proto\x12\x06plugin\"\x14\n" +
	"\x12GetMetadataRequest\"\xaf\x02\n" +
	"\x13GetMetadataResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"operations\x18\x04 \x03(\tR\n" +
	"operations\x12,\n" +
	"\bplatform\x18\x05 \x01(\v2\x10.plugin.PlatformR\bplatform\x12?\n" +
	"\x06config\x18\x06 \x03(\v2'.plugin.GetMetadataResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\bPlatform\x12\x0e\n" +
	"\x02os\x18\x01 \x03(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x03(\tR\x04arch\"\xe0\x01\n" +
	"\x0eExecuteRequest\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x121\n" +
	"\x03env\x18\x03 \x03(\v2\x1f.plugin.ExecuteRequest.EnvEntryR\x03env\x121\n" +
	"\x15host_config_broker_id\x18\x04 \x01(\rR\x12hostConfigBrokerId\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x01\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06stdout\x18\x01 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x02 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x128\n" +
	"\n" +
	"finalizers\x18\x05 \x03(\v2\x18.plugin.FinalizerRequestR\n" +
	"finalizers\"\x95\x01\n" +
	"\x15ValidateConfigRequest\x12A\n" +
	"\x06config\x18\x01 \x03(\v2).plugin.ValidateConfigRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x16ValidateConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x12\n" +
	"\x10GetSchemaRequest\"\xcf\x01\n" +
	"\x11GetSchemaResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12I\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2).plugin.GetSchemaResponse.PropertiesEntryR\n" +
	"properties\x1aU\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.plugin.SchemaPropertyR\x05value:\x028\x01\"|\n" +
	"\x0eSchemaProperty\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x18\n" +
	"\adefault\x18\x04 \x01(\tR\adefault\"\x1b\n" +
	"\x19GetEffectiveConfigRequest\"=\n" +
	"\x1aGetEffectiveConfigResponse\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\"X\n" +
	"\x10FinalizerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args2\xa1\x02\n" +
	"\bDSPlugin\x12F\n" +
	"\vGetMetadata\x12\x1a.plugin.GetMetadataRequest\x1a\x1b.plugin.GetMetadataResponse\x12:\n" +
	"\aExecute\x12\x16.plugin.ExecuteRequest\x1a\x17.plugin.ExecuteResponse\x12O\n" +
	"\x0eValidateConfig\x12\x1d.plugin.ValidateConfigRequest\x1a\x1e.plugin.ValidateConfigResponse\x12@\n" +
	"\tGetSchema\x12\x18.plugin.GetSchemaRequest\x1a\x19.plugin.GetSchemaResponse2i\n" +
	"\n" +
	"HostConfig\x12[\n" +
	"\x12GetEffectiveConfig\x12!.plugin.GetEffectiveConfigRequest\x1a\".plugin.GetEffectiveConfigResponseB+Z)github.com/delivery-station/ds/pkg/pluginb\x06proto3"

var (
	file_pkg_plugin_plugin_proto_rawDescOnce sync.Once
	file_pkg_plugin_plugin_proto_rawDescData []byte
)

func file_pkg_plugin_plugin_proto_rawDescGZIP() []byte {
	file_pkg_plugin_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_plugin_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugin_plugin_proto_rawDesc), len(file_pkg_plugin_plugin_proto_rawDesc)))
	})
	return file_pkg_plugin_plugin_proto_rawDescData
}

var file_pkg_plugin_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_plugin_plugin_proto_goTypes = []any{
	(*GetMetadataRequest)(nil),         // 0: plugin.GetMetadataRequest
	(*GetMetadataResponse)(nil),        // 1: plugin.GetMetadataResponse
	(*Platform)(nil),                   // 2: plugin.Platform
	(*ExecuteRequest)(nil),             // 3: plugin.ExecuteRequest
	(*ExecuteResponse)(nil),            // 4: plugin.ExecuteResponse
	(*ValidateConfigRequest)(nil),      // 5: plugin.ValidateConfigRequest
	(*ValidateConfigResponse)(nil),     // 6: plugin.ValidateConfigResponse
	(*GetSchemaRequest)(nil),           // 7: plugin.GetSchemaRequest
	(*GetSchemaResponse)(nil),          // 8: plugin.GetSchemaResponse
	(*SchemaProperty)(nil),             // 9: plugin.SchemaProperty
	(*GetEffectiveConfigRequest)(nil),  // 10: plugin.GetEffectiveConfigRequest
	(*GetEffectiveConfigResponse)(nil), // 11: plugin.GetEffectiveConfigResponse
	(*FinalizerRequest)(nil),           // 12: plugin.FinalizerRequest
	nil,                                // 13: plugin.GetMetadataResponse.ConfigEntry
	nil,                                // 14: plugin.ExecuteRequest.EnvEntry
	nil,                                // 15: plugin.ValidateConfigRequest.ConfigEntry
	nil,                                // 16: plugin.GetSchemaResponse.PropertiesEntry
}
var file_pkg_plugin_plugin_proto_depIdxs = []int32{
	2,  // 0: plugin.GetMetadataResponse.platform:type_name -> plugin.Platform
	13, // 1: plugin.GetMetadataResponse.config:type_name -> plugin.GetMetadataResponse.ConfigEntry
	14, // 2: plugin.ExecuteRequest.env:type_name -> plugin.ExecuteRequest.EnvEntry
	12, // 3: plugin.ExecuteResponse.finalizers:type_name -> plugin.FinalizerRequest
	15, // 4: plugin.ValidateConfigRequest.config:type_name -> plugin.ValidateConfigRequest.ConfigEntry
	16, // 5: plugin.GetSchemaResponse.properties:type_name -> plugin.GetSchemaResponse.PropertiesEntry
	9,  // 6: plugin.GetSchemaResponse.PropertiesEntry.value:type_name -> plugin.SchemaProperty
	0,  // 7: plugin.DSPlugin.GetMetadata:input_type -> plugin.GetMetadataRequest
	3,  // 8: plugin.DSPlugin.Execute:input_type -> plugin.ExecuteRequest
	5,  // 9: plugin.DSPlugin.ValidateConfig:input_type -> plugin.ValidateConfigRequest
	7,  // 10: plugin.DSPlugin.GetSchema:input_type -> plugin.GetSchemaRequest
	10, // 11: plugin.HostConfig.GetEffectiveConfig:input_type -> plugin.GetEffectiveConfigRequest
	1,  // 12: plugin.DSPlugin.GetMetadata:output_type -> plugin.GetMetadataResponse
	4,  // 13: plugin.DSPlugin.Execute:output_type -> plugin.ExecuteResponse
	6,  // 14: plugin.DSPlugin.ValidateConfig:output_type -> plugin.ValidateConfigResponse
	8,  // 15: plugin.DSPlugin.GetSchema:output_type -> plugin.GetSchemaResponse
	11, // 16: plugin.HostConfig.GetEffectiveConfig:output_type -> plugin.GetEffectiveConfigResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_plugin_plugin_proto_init() }
func file_pkg_plugin_plugin_proto_init() {
	if File_pkg_plugin_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugin_plugin_proto_rawDesc), len(file_pkg_plugin_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_plugin_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_plugin_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_plugin_plugin_proto_msgTypes,
	}.Build()
	File_pkg_plugin_plugin_proto = out.File
	file_pkg_plugin_plugin_proto_goTypes = nil
	file_pkg_plugin_plugin_proto_depIdxs = nil
}
